[package]
name = "Rust-log-collector"
version = "0.1.0"
edition = "2024"

[dependencies]
tracing = "0.1.41"
tracing-subscriber = {version = "0.3.19", features = ["json"]}
# clickhouse = { version = "0.13.2", features = ["test-util"] }