services:
  rust-log-collector:
    build: .
    container_name: rust-log-collector
    ports:
      - "8080:8080"
    depends_on:
      - clickhouse
      - vector
    logging:
      driver: "json-file"

  vector:
    image: timberio/vector:0.45.0-alpine
    container_name: vector-log-collector
    volumes:
      - ./vector.yaml:/etc/vector/vector.yaml:ro # <-- copying vector.yaml to docker in Read Only mode 
      - /var/run/docker.sock:/var/run/docker.sock # <-- This allows access to Docker logs

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse_server
    restart: always
    environment:
    - CLICKHOUSE_USER=admin
    - CLICKHOUSE_PASSWORD=admin123
    - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8123"]
      interval: 10s
      retries: 5
      start_period: 20s

volumes:
  clickhouse_data:
